/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package modules.menu.view;

/**
 *
 * @author lluis
 */
public class Config_jFrame extends javax.swing.JFrame {

    /**
     * Creates new form Config_jFrame
     */
    public Config_jFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optDate = new javax.swing.ButtonGroup();
        optDecimals = new javax.swing.ButtonGroup();
        optCurrency = new javax.swing.ButtonGroup();
        optLanguage = new javax.swing.ButtonGroup();
        optFiles = new javax.swing.ButtonGroup();
        optThemes = new javax.swing.ButtonGroup();
        jPanel7 = new javax.swing.JPanel();
        optConfig = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        optDate1 = new javax.swing.JRadioButton();
        optDate2 = new javax.swing.JRadioButton();
        optDate3 = new javax.swing.JRadioButton();
        optDate4 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        optDecimals1 = new javax.swing.JRadioButton();
        optDecimals2 = new javax.swing.JRadioButton();
        optDecimals3 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        optEuros = new javax.swing.JRadioButton();
        optDolars = new javax.swing.JRadioButton();
        optLibras = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        optEn = new javax.swing.JRadioButton();
        optEsp = new javax.swing.JRadioButton();
        optVal = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        optJson = new javax.swing.JRadioButton();
        optXml = new javax.swing.JRadioButton();
        optTxt = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        optMetal = new javax.swing.JRadioButton();
        optWindows = new javax.swing.JRadioButton();
        optMotif = new javax.swing.JRadioButton();
        optNimbus = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnDefault = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        optConfig.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        optDate1.setBackground(new java.awt.Color(255, 255, 255));
        optDate.add(optDate1);
        optDate1.setText("dd/MM/yyyy");

        optDate2.setBackground(new java.awt.Color(255, 255, 255));
        optDate.add(optDate2);
        optDate2.setText("dd-MM-yyyy");

        optDate3.setBackground(new java.awt.Color(255, 255, 255));
        optDate.add(optDate3);
        optDate3.setText("yyyy/MM/dd");

        optDate4.setBackground(new java.awt.Color(255, 255, 255));
        optDate.add(optDate4);
        optDate4.setText("yyyy-MM-dd");

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("¿Que formato de fecha desea utilizar?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(optDate1)
                .addGap(37, 37, 37)
                .addComponent(optDate2)
                .addGap(35, 35, 35)
                .addComponent(optDate3)
                .addGap(37, 37, 37)
                .addComponent(optDate4)
                .addContainerGap(33, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optDate1)
                    .addComponent(optDate2)
                    .addComponent(optDate3)
                    .addComponent(optDate4))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        optConfig.addTab("Formato de Fecha", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        optDecimals1.setBackground(new java.awt.Color(255, 255, 255));
        optDecimals.add(optDecimals1);
        optDecimals1.setText("1");

        optDecimals2.setBackground(new java.awt.Color(255, 255, 255));
        optDecimals.add(optDecimals2);
        optDecimals2.setText("2 ");

        optDecimals3.setBackground(new java.awt.Color(255, 255, 255));
        optDecimals.add(optDecimals3);
        optDecimals3.setText("3");

        jLabel2.setText("¿Cuantos Decimales quieres utilizar?");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(optDecimals1)
                        .addGap(46, 46, 46)
                        .addComponent(optDecimals2)
                        .addGap(77, 77, 77)
                        .addComponent(optDecimals3))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optDecimals1)
                    .addComponent(optDecimals2)
                    .addComponent(optDecimals3))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        optConfig.addTab("Decimales", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        optEuros.setBackground(new java.awt.Color(255, 255, 255));
        optCurrency.add(optEuros);
        optEuros.setText("€");

        optDolars.setBackground(new java.awt.Color(255, 255, 255));
        optCurrency.add(optDolars);
        optDolars.setText("$");

        optLibras.setBackground(new java.awt.Color(255, 255, 255));
        optCurrency.add(optLibras);
        optLibras.setText("£");

        jLabel4.setText("Elige la moneda con la que quieres que trabaje la aplicacion");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(optEuros)
                        .addGap(26, 26, 26)
                        .addComponent(optDolars)
                        .addGap(32, 32, 32)
                        .addComponent(optLibras, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optEuros)
                    .addComponent(optDolars)
                    .addComponent(optLibras))
                .addContainerGap(41, Short.MAX_VALUE))
        );

        optConfig.addTab("Moneda", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        optEn.setBackground(new java.awt.Color(255, 255, 255));
        optLanguage.add(optEn);
        optEn.setText("Ingles");

        optEsp.setBackground(new java.awt.Color(255, 255, 255));
        optLanguage.add(optEsp);
        optEsp.setText("Español");

        optVal.setBackground(new java.awt.Color(255, 255, 255));
        optLanguage.add(optVal);
        optVal.setText("Valenciano");

        jLabel3.setText("¿En que idioma desea la aplicacion?");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(optEn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(optEsp, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(optVal)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optEn)
                    .addComponent(optEsp)
                    .addComponent(optVal))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        optConfig.addTab("Idioma", jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        optJson.setBackground(new java.awt.Color(255, 255, 255));
        optFiles.add(optJson);
        optJson.setText("JSON");

        optXml.setBackground(new java.awt.Color(255, 255, 255));
        optFiles.add(optXml);
        optXml.setText("XML");

        optTxt.setBackground(new java.awt.Color(255, 255, 255));
        optFiles.add(optTxt);
        optTxt.setText("TXT");

        jLabel5.setText("Elige el formato con el que quieres guardar los datos");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(optJson, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(optTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58)
                        .addComponent(optXml)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optJson)
                    .addComponent(optXml)
                    .addComponent(optTxt))
                .addGap(42, 42, 42))
        );

        optConfig.addTab("Ficheros", jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        optMetal.setBackground(new java.awt.Color(255, 255, 255));
        optThemes.add(optMetal);
        optMetal.setText("Metal");

        optWindows.setBackground(new java.awt.Color(255, 255, 255));
        optThemes.add(optWindows);
        optWindows.setText("Windows");

        optMotif.setBackground(new java.awt.Color(255, 255, 255));
        optThemes.add(optMotif);
        optMotif.setText("Motif");

        optNimbus.setBackground(new java.awt.Color(255, 255, 255));
        optThemes.add(optNimbus);
        optNimbus.setText("Nimbus");

        jLabel6.setText("Elige el tema que desees utilizar");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(optMetal)
                        .addGap(42, 42, 42)
                        .addComponent(optWindows, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(optMotif, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(optNimbus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optMetal)
                    .addComponent(optWindows)
                    .addComponent(optMotif)
                    .addComponent(optNimbus))
                .addGap(37, 37, 37))
        );

        optConfig.addTab("Temas", jPanel6);

        btnSave.setText("Guardar Configuracion");

        btnVolver.setText("Volver");

        btnDefault.setText("Configuracion Predeterminada");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(optConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(optConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnDefault;
    public static javax.swing.JButton btnSave;
    public static javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    public static javax.swing.JTabbedPane optConfig;
    public static javax.swing.ButtonGroup optCurrency;
    public static javax.swing.ButtonGroup optDate;
    public static javax.swing.JRadioButton optDate1;
    public static javax.swing.JRadioButton optDate2;
    public static javax.swing.JRadioButton optDate3;
    public static javax.swing.JRadioButton optDate4;
    public static javax.swing.ButtonGroup optDecimals;
    public static javax.swing.JRadioButton optDecimals1;
    public static javax.swing.JRadioButton optDecimals2;
    public static javax.swing.JRadioButton optDecimals3;
    public static javax.swing.JRadioButton optDolars;
    public static javax.swing.JRadioButton optEn;
    public static javax.swing.JRadioButton optEsp;
    public static javax.swing.JRadioButton optEuros;
    public static javax.swing.ButtonGroup optFiles;
    public static javax.swing.JRadioButton optJson;
    public static javax.swing.ButtonGroup optLanguage;
    public static javax.swing.JRadioButton optLibras;
    public static javax.swing.JRadioButton optMetal;
    public static javax.swing.JRadioButton optMotif;
    public static javax.swing.JRadioButton optNimbus;
    public static javax.swing.ButtonGroup optThemes;
    public static javax.swing.JRadioButton optTxt;
    public static javax.swing.JRadioButton optVal;
    public static javax.swing.JRadioButton optWindows;
    public static javax.swing.JRadioButton optXml;
    // End of variables declaration//GEN-END:variables
}
